from PyQt5 import QtCore, QtGui, QtWidgets, QtTest
import os
import joblib
import numpy as np
import time
from Sudoku import Sudoku
import math
import sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(826, 682)
        MainWindow.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setFamily("System")
        font.setPointSize(80)
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cell00 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell00.setGeometry(QtCore.QRect(200, 40, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell00.setFont(font)
        self.cell00.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell00.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell00.setWrapping(False)
        self.cell00.setAlignment(QtCore.Qt.AlignCenter)
        self.cell00.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell00.setMinimum(0)
        self.cell00.setMaximum(9)
        self.cell00.setProperty("value", 0)
        self.cell00.setObjectName("cell00")
        self.cell01 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell01.setGeometry(QtCore.QRect(250, 40, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell01.setFont(font)
        self.cell01.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell01.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell01.setWrapping(False)
        self.cell01.setAlignment(QtCore.Qt.AlignCenter)
        self.cell01.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell01.setMinimum(0)
        self.cell01.setMaximum(9)
        self.cell01.setObjectName("cell01")
        self.cell02 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell02.setGeometry(QtCore.QRect(300, 40, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell02.setFont(font)
        self.cell02.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell02.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell02.setWrapping(False)
        self.cell02.setAlignment(QtCore.Qt.AlignCenter)
        self.cell02.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell02.setMinimum(0)
        self.cell02.setMaximum(9)
        self.cell02.setObjectName("cell02")
        self.cell03 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell03.setGeometry(QtCore.QRect(350, 40, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell03.setFont(font)
        self.cell03.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell03.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell03.setWrapping(False)
        self.cell03.setAlignment(QtCore.Qt.AlignCenter)
        self.cell03.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell03.setMinimum(0)
        self.cell03.setMaximum(9)
        self.cell03.setObjectName("cell03")
        self.cell04 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell04.setGeometry(QtCore.QRect(400, 40, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell04.setFont(font)
        self.cell04.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell04.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell04.setWrapping(False)
        self.cell04.setAlignment(QtCore.Qt.AlignCenter)
        self.cell04.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell04.setMinimum(0)
        self.cell04.setMaximum(9)
        self.cell04.setObjectName("cell04")
        self.cell05 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell05.setGeometry(QtCore.QRect(450, 40, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell05.setFont(font)
        self.cell05.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell05.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell05.setWrapping(False)
        self.cell05.setAlignment(QtCore.Qt.AlignCenter)
        self.cell05.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell05.setMinimum(0)
        self.cell05.setMaximum(9)
        self.cell05.setObjectName("cell05")
        self.cell06 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell06.setGeometry(QtCore.QRect(500, 40, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell06.setFont(font)
        self.cell06.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell06.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell06.setWrapping(False)
        self.cell06.setAlignment(QtCore.Qt.AlignCenter)
        self.cell06.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell06.setMinimum(0)
        self.cell06.setMaximum(9)
        self.cell06.setObjectName("cell06")
        self.cell07 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell07.setGeometry(QtCore.QRect(550, 40, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell07.setFont(font)
        self.cell07.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell07.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell07.setWrapping(False)
        self.cell07.setAlignment(QtCore.Qt.AlignCenter)
        self.cell07.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell07.setMinimum(0)
        self.cell07.setMaximum(9)
        self.cell07.setObjectName("cell07")
        self.cell08 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell08.setGeometry(QtCore.QRect(600, 40, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell08.setFont(font)
        self.cell08.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell08.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell08.setWrapping(False)
        self.cell08.setAlignment(QtCore.Qt.AlignCenter)
        self.cell08.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell08.setMinimum(0)
        self.cell08.setMaximum(9)
        self.cell08.setObjectName("cell08")
        self.cell14 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell14.setGeometry(QtCore.QRect(400, 90, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell14.setFont(font)
        self.cell14.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell14.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell14.setWrapping(False)
        self.cell14.setAlignment(QtCore.Qt.AlignCenter)
        self.cell14.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell14.setMinimum(0)
        self.cell14.setMaximum(9)
        self.cell14.setObjectName("cell14")
        self.cell10 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell10.setGeometry(QtCore.QRect(200, 90, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell10.setFont(font)
        self.cell10.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell10.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell10.setWrapping(False)
        self.cell10.setAlignment(QtCore.Qt.AlignCenter)
        self.cell10.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell10.setMinimum(0)
        self.cell10.setMaximum(9)
        self.cell10.setObjectName("cell10")
        self.cell18 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell18.setGeometry(QtCore.QRect(600, 90, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell18.setFont(font)
        self.cell18.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell18.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell18.setWrapping(False)
        self.cell18.setAlignment(QtCore.Qt.AlignCenter)
        self.cell18.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell18.setMinimum(0)
        self.cell18.setMaximum(9)
        self.cell18.setObjectName("cell18")
        self.cell15 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell15.setGeometry(QtCore.QRect(450, 90, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell15.setFont(font)
        self.cell15.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell15.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell15.setWrapping(False)
        self.cell15.setAlignment(QtCore.Qt.AlignCenter)
        self.cell15.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell15.setMinimum(0)
        self.cell15.setMaximum(9)
        self.cell15.setObjectName("cell15")
        self.cell16 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell16.setGeometry(QtCore.QRect(500, 90, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell16.setFont(font)
        self.cell16.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell16.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell16.setWrapping(False)
        self.cell16.setAlignment(QtCore.Qt.AlignCenter)
        self.cell16.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell16.setMinimum(0)
        self.cell16.setMaximum(9)
        self.cell16.setObjectName("cell16")
        self.cell11 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell11.setGeometry(QtCore.QRect(250, 90, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell11.setFont(font)
        self.cell11.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell11.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell11.setWrapping(False)
        self.cell11.setAlignment(QtCore.Qt.AlignCenter)
        self.cell11.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell11.setMinimum(0)
        self.cell11.setMaximum(9)
        self.cell11.setObjectName("cell11")
        self.cell12 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell12.setGeometry(QtCore.QRect(300, 90, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell12.setFont(font)
        self.cell12.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell12.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell12.setWrapping(False)
        self.cell12.setAlignment(QtCore.Qt.AlignCenter)
        self.cell12.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell12.setMinimum(0)
        self.cell12.setMaximum(9)
        self.cell12.setObjectName("cell12")
        self.cell17 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell17.setGeometry(QtCore.QRect(550, 90, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell17.setFont(font)
        self.cell17.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell17.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell17.setWrapping(False)
        self.cell17.setAlignment(QtCore.Qt.AlignCenter)
        self.cell17.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell17.setMinimum(0)
        self.cell17.setMaximum(9)
        self.cell17.setObjectName("cell17")
        self.cell13 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell13.setGeometry(QtCore.QRect(350, 90, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell13.setFont(font)
        self.cell13.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell13.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell13.setWrapping(False)
        self.cell13.setAlignment(QtCore.Qt.AlignCenter)
        self.cell13.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell13.setMinimum(0)
        self.cell13.setMaximum(9)
        self.cell13.setObjectName("cell13")
        self.cell24 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell24.setGeometry(QtCore.QRect(400, 140, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell24.setFont(font)
        self.cell24.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell24.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell24.setWrapping(False)
        self.cell24.setAlignment(QtCore.Qt.AlignCenter)
        self.cell24.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell24.setMinimum(0)
        self.cell24.setMaximum(9)
        self.cell24.setObjectName("cell24")
        self.cell20 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell20.setGeometry(QtCore.QRect(200, 140, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell20.setFont(font)
        self.cell20.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell20.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell20.setWrapping(False)
        self.cell20.setAlignment(QtCore.Qt.AlignCenter)
        self.cell20.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell20.setMinimum(0)
        self.cell20.setMaximum(9)
        self.cell20.setObjectName("cell20")
        self.cell28 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell28.setGeometry(QtCore.QRect(600, 140, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell28.setFont(font)
        self.cell28.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell28.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell28.setWrapping(False)
        self.cell28.setAlignment(QtCore.Qt.AlignCenter)
        self.cell28.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell28.setMinimum(0)
        self.cell28.setMaximum(9)
        self.cell28.setObjectName("cell28")
        self.cell25 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell25.setGeometry(QtCore.QRect(450, 140, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell25.setFont(font)
        self.cell25.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell25.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell25.setWrapping(False)
        self.cell25.setAlignment(QtCore.Qt.AlignCenter)
        self.cell25.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell25.setMinimum(0)
        self.cell25.setMaximum(9)
        self.cell25.setObjectName("cell25")
        self.cell26 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell26.setGeometry(QtCore.QRect(500, 140, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell26.setFont(font)
        self.cell26.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell26.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell26.setWrapping(False)
        self.cell26.setAlignment(QtCore.Qt.AlignCenter)
        self.cell26.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell26.setMinimum(0)
        self.cell26.setMaximum(9)
        self.cell26.setObjectName("cell26")
        self.cell21 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell21.setGeometry(QtCore.QRect(250, 140, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell21.setFont(font)
        self.cell21.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell21.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell21.setWrapping(False)
        self.cell21.setAlignment(QtCore.Qt.AlignCenter)
        self.cell21.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell21.setMinimum(0)
        self.cell21.setMaximum(9)
        self.cell21.setObjectName("cell21")
        self.cell22 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell22.setGeometry(QtCore.QRect(300, 140, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell22.setFont(font)
        self.cell22.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell22.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell22.setWrapping(False)
        self.cell22.setAlignment(QtCore.Qt.AlignCenter)
        self.cell22.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell22.setMinimum(0)
        self.cell22.setMaximum(9)
        self.cell22.setObjectName("cell22")
        self.cell27 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell27.setGeometry(QtCore.QRect(550, 140, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell27.setFont(font)
        self.cell27.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell27.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell27.setWrapping(False)
        self.cell27.setAlignment(QtCore.Qt.AlignCenter)
        self.cell27.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell27.setMinimum(0)
        self.cell27.setMaximum(9)
        self.cell27.setObjectName("cell27")
        self.cell23 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell23.setGeometry(QtCore.QRect(350, 140, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell23.setFont(font)
        self.cell23.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell23.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell23.setWrapping(False)
        self.cell23.setAlignment(QtCore.Qt.AlignCenter)
        self.cell23.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell23.setMinimum(0)
        self.cell23.setMaximum(9)
        self.cell23.setObjectName("cell23")
        self.cell36 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell36.setGeometry(QtCore.QRect(500, 190, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell36.setFont(font)
        self.cell36.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell36.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell36.setWrapping(False)
        self.cell36.setAlignment(QtCore.Qt.AlignCenter)
        self.cell36.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell36.setMinimum(0)
        self.cell36.setMaximum(9)
        self.cell36.setObjectName("cell36")
        self.cell58 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell58.setGeometry(QtCore.QRect(600, 290, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell58.setFont(font)
        self.cell58.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell58.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell58.setWrapping(False)
        self.cell58.setAlignment(QtCore.Qt.AlignCenter)
        self.cell58.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell58.setMinimum(0)
        self.cell58.setMaximum(9)
        self.cell58.setObjectName("cell58")
        self.cell41 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell41.setGeometry(QtCore.QRect(250, 240, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell41.setFont(font)
        self.cell41.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell41.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell41.setWrapping(False)
        self.cell41.setAlignment(QtCore.Qt.AlignCenter)
        self.cell41.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell41.setMinimum(0)
        self.cell41.setMaximum(9)
        self.cell41.setObjectName("cell41")
        self.cell53 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell53.setGeometry(QtCore.QRect(350, 290, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell53.setFont(font)
        self.cell53.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell53.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell53.setWrapping(False)
        self.cell53.setAlignment(QtCore.Qt.AlignCenter)
        self.cell53.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell53.setMinimum(0)
        self.cell53.setMaximum(9)
        self.cell53.setObjectName("cell53")
        self.cell52 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell52.setGeometry(QtCore.QRect(300, 290, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell52.setFont(font)
        self.cell52.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell52.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell52.setWrapping(False)
        self.cell52.setAlignment(QtCore.Qt.AlignCenter)
        self.cell52.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell52.setMinimum(0)
        self.cell52.setMaximum(9)
        self.cell52.setObjectName("cell52")
        self.cell33 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell33.setGeometry(QtCore.QRect(350, 190, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell33.setFont(font)
        self.cell33.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell33.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell33.setWrapping(False)
        self.cell33.setAlignment(QtCore.Qt.AlignCenter)
        self.cell33.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell33.setMinimum(0)
        self.cell33.setMaximum(9)
        self.cell33.setObjectName("cell33")
        self.cell40 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell40.setGeometry(QtCore.QRect(200, 240, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell40.setFont(font)
        self.cell40.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell40.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell40.setWrapping(False)
        self.cell40.setAlignment(QtCore.Qt.AlignCenter)
        self.cell40.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell40.setMinimum(0)
        self.cell40.setMaximum(9)
        self.cell40.setObjectName("cell40")
        self.cell57 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell57.setGeometry(QtCore.QRect(550, 290, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell57.setFont(font)
        self.cell57.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell57.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell57.setWrapping(False)
        self.cell57.setAlignment(QtCore.Qt.AlignCenter)
        self.cell57.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell57.setMinimum(0)
        self.cell57.setMaximum(9)
        self.cell57.setObjectName("cell57")
        self.cell44 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell44.setGeometry(QtCore.QRect(400, 240, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell44.setFont(font)
        self.cell44.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell44.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell44.setWrapping(False)
        self.cell44.setAlignment(QtCore.Qt.AlignCenter)
        self.cell44.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell44.setMinimum(0)
        self.cell44.setMaximum(9)
        self.cell44.setObjectName("cell44")
        self.cell43 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell43.setGeometry(QtCore.QRect(350, 240, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell43.setFont(font)
        self.cell43.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell43.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell43.setWrapping(False)
        self.cell43.setAlignment(QtCore.Qt.AlignCenter)
        self.cell43.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell43.setMinimum(0)
        self.cell43.setMaximum(9)
        self.cell43.setObjectName("cell43")
        self.cell46 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell46.setGeometry(QtCore.QRect(500, 240, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell46.setFont(font)
        self.cell46.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell46.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell46.setWrapping(False)
        self.cell46.setAlignment(QtCore.Qt.AlignCenter)
        self.cell46.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell46.setMinimum(0)
        self.cell46.setMaximum(9)
        self.cell46.setObjectName("cell46")
        self.cell42 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell42.setGeometry(QtCore.QRect(300, 240, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell42.setFont(font)
        self.cell42.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell42.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell42.setWrapping(False)
        self.cell42.setAlignment(QtCore.Qt.AlignCenter)
        self.cell42.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell42.setMinimum(0)
        self.cell42.setMaximum(9)
        self.cell42.setObjectName("cell42")
        self.cell56 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell56.setGeometry(QtCore.QRect(500, 290, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell56.setFont(font)
        self.cell56.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell56.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell56.setWrapping(False)
        self.cell56.setAlignment(QtCore.Qt.AlignCenter)
        self.cell56.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell56.setMinimum(0)
        self.cell56.setMaximum(9)
        self.cell56.setObjectName("cell56")
        self.cell54 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell54.setGeometry(QtCore.QRect(400, 290, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell54.setFont(font)
        self.cell54.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell54.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell54.setWrapping(False)
        self.cell54.setAlignment(QtCore.Qt.AlignCenter)
        self.cell54.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell54.setMinimum(0)
        self.cell54.setMaximum(9)
        self.cell54.setObjectName("cell54")
        self.cell48 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell48.setGeometry(QtCore.QRect(600, 240, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell48.setFont(font)
        self.cell48.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell48.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell48.setWrapping(False)
        self.cell48.setAlignment(QtCore.Qt.AlignCenter)
        self.cell48.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell48.setMinimum(0)
        self.cell48.setMaximum(9)
        self.cell48.setObjectName("cell48")
        self.cell32 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell32.setGeometry(QtCore.QRect(300, 190, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell32.setFont(font)
        self.cell32.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell32.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell32.setWrapping(False)
        self.cell32.setAlignment(QtCore.Qt.AlignCenter)
        self.cell32.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell32.setMinimum(0)
        self.cell32.setMaximum(9)
        self.cell32.setObjectName("cell32")
        self.cell30 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell30.setGeometry(QtCore.QRect(200, 190, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell30.setFont(font)
        self.cell30.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell30.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell30.setWrapping(False)
        self.cell30.setAlignment(QtCore.Qt.AlignCenter)
        self.cell30.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell30.setMinimum(0)
        self.cell30.setMaximum(9)
        self.cell30.setObjectName("cell30")
        self.cell38 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell38.setGeometry(QtCore.QRect(600, 190, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell38.setFont(font)
        self.cell38.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell38.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell38.setWrapping(False)
        self.cell38.setAlignment(QtCore.Qt.AlignCenter)
        self.cell38.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell38.setMinimum(0)
        self.cell38.setMaximum(9)
        self.cell38.setObjectName("cell38")
        self.cell37 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell37.setGeometry(QtCore.QRect(550, 190, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell37.setFont(font)
        self.cell37.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell37.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell37.setWrapping(False)
        self.cell37.setAlignment(QtCore.Qt.AlignCenter)
        self.cell37.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell37.setMinimum(0)
        self.cell37.setMaximum(9)
        self.cell37.setObjectName("cell37")
        self.cell51 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell51.setGeometry(QtCore.QRect(250, 290, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell51.setFont(font)
        self.cell51.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell51.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell51.setWrapping(False)
        self.cell51.setAlignment(QtCore.Qt.AlignCenter)
        self.cell51.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell51.setMinimum(0)
        self.cell51.setMaximum(9)
        self.cell51.setObjectName("cell51")
        self.cell50 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell50.setGeometry(QtCore.QRect(200, 290, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell50.setFont(font)
        self.cell50.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell50.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell50.setWrapping(False)
        self.cell50.setAlignment(QtCore.Qt.AlignCenter)
        self.cell50.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell50.setMinimum(0)
        self.cell50.setMaximum(9)
        self.cell50.setObjectName("cell50")
        self.cell45 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell45.setGeometry(QtCore.QRect(450, 240, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell45.setFont(font)
        self.cell45.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell45.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell45.setWrapping(False)
        self.cell45.setAlignment(QtCore.Qt.AlignCenter)
        self.cell45.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell45.setMinimum(0)
        self.cell45.setMaximum(9)
        self.cell45.setObjectName("cell45")
        self.cell31 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell31.setGeometry(QtCore.QRect(250, 190, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell31.setFont(font)
        self.cell31.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell31.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell31.setWrapping(False)
        self.cell31.setAlignment(QtCore.Qt.AlignCenter)
        self.cell31.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell31.setMinimum(0)
        self.cell31.setMaximum(9)
        self.cell31.setObjectName("cell31")
        self.cell55 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell55.setGeometry(QtCore.QRect(450, 290, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell55.setFont(font)
        self.cell55.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell55.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell55.setWrapping(False)
        self.cell55.setAlignment(QtCore.Qt.AlignCenter)
        self.cell55.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell55.setMinimum(0)
        self.cell55.setMaximum(9)
        self.cell55.setObjectName("cell55")
        self.cell34 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell34.setGeometry(QtCore.QRect(400, 190, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell34.setFont(font)
        self.cell34.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell34.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell34.setWrapping(False)
        self.cell34.setAlignment(QtCore.Qt.AlignCenter)
        self.cell34.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell34.setMinimum(0)
        self.cell34.setMaximum(9)
        self.cell34.setObjectName("cell34")
        self.cell47 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell47.setGeometry(QtCore.QRect(550, 240, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell47.setFont(font)
        self.cell47.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell47.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell47.setWrapping(False)
        self.cell47.setAlignment(QtCore.Qt.AlignCenter)
        self.cell47.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell47.setMinimum(0)
        self.cell47.setMaximum(9)
        self.cell47.setObjectName("cell47")
        self.cell35 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell35.setGeometry(QtCore.QRect(450, 190, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell35.setFont(font)
        self.cell35.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell35.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell35.setWrapping(False)
        self.cell35.setAlignment(QtCore.Qt.AlignCenter)
        self.cell35.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell35.setMinimum(0)
        self.cell35.setMaximum(9)
        self.cell35.setObjectName("cell35")
        self.cell61 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell61.setGeometry(QtCore.QRect(250, 340, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell61.setFont(font)
        self.cell61.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell61.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell61.setWrapping(False)
        self.cell61.setAlignment(QtCore.Qt.AlignCenter)
        self.cell61.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell61.setMinimum(0)
        self.cell61.setMaximum(9)
        self.cell61.setObjectName("cell61")
        self.cell83 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell83.setGeometry(QtCore.QRect(350, 440, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell83.setFont(font)
        self.cell83.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell83.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell83.setWrapping(False)
        self.cell83.setAlignment(QtCore.Qt.AlignCenter)
        self.cell83.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell83.setMinimum(0)
        self.cell83.setMaximum(9)
        self.cell83.setObjectName("cell83")
        self.cell60 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell60.setGeometry(QtCore.QRect(200, 340, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell60.setFont(font)
        self.cell60.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell60.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell60.setWrapping(False)
        self.cell60.setAlignment(QtCore.Qt.AlignCenter)
        self.cell60.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell60.setMinimum(0)
        self.cell60.setMaximum(9)
        self.cell60.setObjectName("cell60")
        self.cell65 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell65.setGeometry(QtCore.QRect(450, 340, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell65.setFont(font)
        self.cell65.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell65.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell65.setWrapping(False)
        self.cell65.setAlignment(QtCore.Qt.AlignCenter)
        self.cell65.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell65.setMinimum(0)
        self.cell65.setMaximum(9)
        self.cell65.setObjectName("cell65")
        self.cell73 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell73.setGeometry(QtCore.QRect(350, 390, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell73.setFont(font)
        self.cell73.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell73.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell73.setWrapping(False)
        self.cell73.setAlignment(QtCore.Qt.AlignCenter)
        self.cell73.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell73.setMinimum(0)
        self.cell73.setMaximum(9)
        self.cell73.setObjectName("cell73")
        self.cell66 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell66.setGeometry(QtCore.QRect(500, 340, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell66.setFont(font)
        self.cell66.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell66.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell66.setWrapping(False)
        self.cell66.setAlignment(QtCore.Qt.AlignCenter)
        self.cell66.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell66.setMinimum(0)
        self.cell66.setMaximum(9)
        self.cell66.setObjectName("cell66")
        self.cell78 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell78.setGeometry(QtCore.QRect(600, 390, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell78.setFont(font)
        self.cell78.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell78.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell78.setWrapping(False)
        self.cell78.setAlignment(QtCore.Qt.AlignCenter)
        self.cell78.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell78.setMinimum(0)
        self.cell78.setMaximum(9)
        self.cell78.setObjectName("cell78")
        self.cell76 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell76.setGeometry(QtCore.QRect(500, 390, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell76.setFont(font)
        self.cell76.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell76.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell76.setWrapping(False)
        self.cell76.setAlignment(QtCore.Qt.AlignCenter)
        self.cell76.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell76.setMinimum(0)
        self.cell76.setMaximum(9)
        self.cell76.setObjectName("cell76")
        self.cell77 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell77.setGeometry(QtCore.QRect(550, 390, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell77.setFont(font)
        self.cell77.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell77.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell77.setWrapping(False)
        self.cell77.setAlignment(QtCore.Qt.AlignCenter)
        self.cell77.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell77.setMinimum(0)
        self.cell77.setMaximum(9)
        self.cell77.setObjectName("cell77")
        self.cell64 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell64.setGeometry(QtCore.QRect(400, 340, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell64.setFont(font)
        self.cell64.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell64.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell64.setWrapping(False)
        self.cell64.setAlignment(QtCore.Qt.AlignCenter)
        self.cell64.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell64.setMinimum(0)
        self.cell64.setMaximum(9)
        self.cell64.setObjectName("cell64")
        self.cell67 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell67.setGeometry(QtCore.QRect(550, 340, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell67.setFont(font)
        self.cell67.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell67.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell67.setWrapping(False)
        self.cell67.setAlignment(QtCore.Qt.AlignCenter)
        self.cell67.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell67.setMinimum(0)
        self.cell67.setMaximum(9)
        self.cell67.setObjectName("cell67")
        self.cell86 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell86.setGeometry(QtCore.QRect(500, 440, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell86.setFont(font)
        self.cell86.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell86.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell86.setWrapping(False)
        self.cell86.setAlignment(QtCore.Qt.AlignCenter)
        self.cell86.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell86.setMinimum(0)
        self.cell86.setMaximum(9)
        self.cell86.setObjectName("cell86")
        self.cell68 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell68.setGeometry(QtCore.QRect(600, 340, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell68.setFont(font)
        self.cell68.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell68.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell68.setWrapping(False)
        self.cell68.setAlignment(QtCore.Qt.AlignCenter)
        self.cell68.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell68.setMinimum(0)
        self.cell68.setMaximum(9)
        self.cell68.setObjectName("cell68")
        self.cell81 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell81.setGeometry(QtCore.QRect(250, 440, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell81.setFont(font)
        self.cell81.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell81.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell81.setWrapping(False)
        self.cell81.setAlignment(QtCore.Qt.AlignCenter)
        self.cell81.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell81.setMinimum(0)
        self.cell81.setMaximum(9)
        self.cell81.setObjectName("cell81")
        self.cell71 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell71.setGeometry(QtCore.QRect(250, 390, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell71.setFont(font)
        self.cell71.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell71.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell71.setWrapping(False)
        self.cell71.setAlignment(QtCore.Qt.AlignCenter)
        self.cell71.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell71.setMinimum(0)
        self.cell71.setMaximum(9)
        self.cell71.setObjectName("cell71")
        self.cell72 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell72.setGeometry(QtCore.QRect(300, 390, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell72.setFont(font)
        self.cell72.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell72.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell72.setWrapping(False)
        self.cell72.setAlignment(QtCore.Qt.AlignCenter)
        self.cell72.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell72.setMinimum(0)
        self.cell72.setMaximum(9)
        self.cell72.setObjectName("cell72")
        self.cell87 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell87.setGeometry(QtCore.QRect(550, 440, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell87.setFont(font)
        self.cell87.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell87.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell87.setWrapping(False)
        self.cell87.setAlignment(QtCore.Qt.AlignCenter)
        self.cell87.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell87.setMinimum(0)
        self.cell87.setMaximum(9)
        self.cell87.setObjectName("cell87")
        self.cell84 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell84.setGeometry(QtCore.QRect(400, 440, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell84.setFont(font)
        self.cell84.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell84.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell84.setWrapping(False)
        self.cell84.setAlignment(QtCore.Qt.AlignCenter)
        self.cell84.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell84.setMinimum(0)
        self.cell84.setMaximum(9)
        self.cell84.setObjectName("cell84")
        self.cell85 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell85.setGeometry(QtCore.QRect(450, 440, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell85.setFont(font)
        self.cell85.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell85.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell85.setWrapping(False)
        self.cell85.setAlignment(QtCore.Qt.AlignCenter)
        self.cell85.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell85.setMinimum(0)
        self.cell85.setMaximum(9)
        self.cell85.setObjectName("cell85")
        self.cell70 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell70.setGeometry(QtCore.QRect(200, 390, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell70.setFont(font)
        self.cell70.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell70.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell70.setWrapping(False)
        self.cell70.setAlignment(QtCore.Qt.AlignCenter)
        self.cell70.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell70.setMinimum(0)
        self.cell70.setMaximum(9)
        self.cell70.setObjectName("cell70")
        self.cell80 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell80.setGeometry(QtCore.QRect(200, 440, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell80.setFont(font)
        self.cell80.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell80.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell80.setWrapping(False)
        self.cell80.setAlignment(QtCore.Qt.AlignCenter)
        self.cell80.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell80.setMinimum(0)
        self.cell80.setMaximum(9)
        self.cell80.setObjectName("cell80")
        self.cell62 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell62.setGeometry(QtCore.QRect(300, 340, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell62.setFont(font)
        self.cell62.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell62.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell62.setWrapping(False)
        self.cell62.setAlignment(QtCore.Qt.AlignCenter)
        self.cell62.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell62.setMinimum(0)
        self.cell62.setMaximum(9)
        self.cell62.setObjectName("cell62")
        self.cell74 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell74.setGeometry(QtCore.QRect(400, 390, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell74.setFont(font)
        self.cell74.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell74.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell74.setWrapping(False)
        self.cell74.setAlignment(QtCore.Qt.AlignCenter)
        self.cell74.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell74.setMinimum(0)
        self.cell74.setMaximum(9)
        self.cell74.setObjectName("cell74")
        self.cell82 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell82.setGeometry(QtCore.QRect(300, 440, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell82.setFont(font)
        self.cell82.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell82.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell82.setWrapping(False)
        self.cell82.setAlignment(QtCore.Qt.AlignCenter)
        self.cell82.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell82.setMinimum(0)
        self.cell82.setMaximum(9)
        self.cell82.setObjectName("cell82")
        self.cell63 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell63.setGeometry(QtCore.QRect(350, 340, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell63.setFont(font)
        self.cell63.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell63.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell63.setWrapping(False)
        self.cell63.setAlignment(QtCore.Qt.AlignCenter)
        self.cell63.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell63.setMinimum(0)
        self.cell63.setMaximum(9)
        self.cell63.setObjectName("cell63")
        self.cell75 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell75.setGeometry(QtCore.QRect(450, 390, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell75.setFont(font)
        self.cell75.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell75.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell75.setWrapping(False)
        self.cell75.setAlignment(QtCore.Qt.AlignCenter)
        self.cell75.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell75.setMinimum(0)
        self.cell75.setMaximum(9)
        self.cell75.setObjectName("cell75")
        self.cell88 = QtWidgets.QSpinBox(self.centralwidget)
        self.cell88.setGeometry(QtCore.QRect(600, 440, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semilight")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.cell88.setFont(font)
        self.cell88.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.cell88.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.cell88.setWrapping(False)
        self.cell88.setAlignment(QtCore.Qt.AlignCenter)
        self.cell88.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cell88.setMinimum(0)
        self.cell88.setMaximum(9)
        self.cell88.setObjectName("cell88")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(190, 40, 20, 451))
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(3)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(340, 40, 20, 451))
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(3)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(490, 40, 20, 451))
        self.line_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_3.setLineWidth(3)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(640, 40, 20, 451))
        self.line_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_4.setLineWidth(3)
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(200, 480, 451, 16))
        self.line_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_5.setLineWidth(3)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(200, 330, 451, 16))
        self.line_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_6.setLineWidth(3)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setGeometry(QtCore.QRect(200, 180, 451, 16))
        self.line_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_7.setLineWidth(3)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setGeometry(QtCore.QRect(200, 30, 451, 16))
        self.line_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_8.setLineWidth(3)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setObjectName("line_8")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(520, 510, 131, 61))
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setMouseTracking(True)
        self.pushButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton.setAutoDefault(True)
        self.pushButton.setDefault(True)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.resolve(np.zeros((9,9)), False))
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(200, 510, 131, 61))
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setMouseTracking(True)
        self.pushButton_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_2.setAutoDefault(True)
        self.pushButton_2.setDefault(True)
        self.pushButton_2.setFlat(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.clicked.connect(self.load)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 220, 331, 71))
        self.label.setStyleSheet("font: 24pt \"Tahoma\";\n"
"color: rgba(255, 255, 255, 0);")
        self.label.setObjectName("label")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(360, 510, 131, 61))
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setMouseTracking(True)
        self.pushButton_3.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_3.setAutoDefault(True)
        self.pushButton_3.setDefault(True)
        self.pushButton_3.setFlat(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.clicked.connect(self.check)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 826, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.row_dict={0:[self.cell00,self.cell01,self.cell02,self.cell03,self.cell04,self.cell05,self.cell06,self.cell07,self.cell08],1:[self.cell10,self.cell11,self.cell12,self.cell13,self.cell14,self.cell15,self.cell16,self.cell17,self.cell18],2:[self.cell20,self.cell21,self.cell22,self.cell23,self.cell24,self.cell25,self.cell26,self.cell27,self.cell28],3:[self.cell30,self.cell31,self.cell32,self.cell33,self.cell34,self.cell35,self.cell36,self.cell37,self.cell38],4:[self.cell40,self.cell41,self.cell42,self.cell43,self.cell44,self.cell45,self.cell46,self.cell47,self.cell48],5:[self.cell50,self.cell51,self.cell52,self.cell53,self.cell54,self.cell55,self.cell56,self.cell57,self.cell58],6:[self.cell60,self.cell61,self.cell62,self.cell63,self.cell64,self.cell65,self.cell66,self.cell67,self.cell68],7:[self.cell70,self.cell71,self.cell72,self.cell73,self.cell74,self.cell75,self.cell76,self.cell77,self.cell78],8:[self.cell80,self.cell81,self.cell82,self.cell83,self.cell84,self.cell85,self.cell86,self.cell87,self.cell88]}
        self.col_dict={0:[self.cell00,self.cell10,self.cell20,self.cell30,self.cell40,self.cell50,self.cell60,self.cell70,self.cell80],1:[self.cell01,self.cell11,self.cell21,self.cell31,self.cell41,self.cell51,self.cell61,self.cell71,self.cell81],2:[self.cell02,self.cell12,self.cell22,self.cell32,self.cell42,self.cell52,self.cell62,self.cell72,self.cell82],3:[self.cell03,self.cell13,self.cell23,self.cell33,self.cell43,self.cell53,self.cell63,self.cell73,self.cell83],4:[self.cell04,self.cell14,self.cell24,self.cell34,self.cell44,self.cell54,self.cell64,self.cell74,self.cell84],5:[self.cell05,self.cell15,self.cell25,self.cell35,self.cell45,self.cell55,self.cell65,self.cell75,self.cell85],6:[self.cell06,self.cell16,self.cell26,self.cell36,self.cell46,self.cell56,self.cell66,self.cell76,self.cell86],7:[self.cell07,self.cell17,self.cell27,self.cell37,self.cell47,self.cell57,self.cell67,self.cell77,self.cell87],8:[self.cell08,self.cell18,self.cell28,self.cell38,self.cell48,self.cell58,self.cell68,self.cell78,self.cell88]}
        self.cuadrant_dict={1:[self.cell00, self.cell01, self.cell02, self.cell10, self.cell11, self.cell12, self.cell20, self.cell21, self.cell22], 2:[self.cell03, self.cell04, self.cell05, self.cell13, self.cell14, self.cell15, self.cell23, self.cell24, self.cell25], 3:[self.cell06, self.cell07, self.cell08, self.cell16, self.cell17, self.cell18, self.cell26, self.cell27, self.cell28], 4:[self.cell30, self.cell31, self.cell32, self.cell40, self.cell41, self.cell42, self.cell50, self.cell51, self.cell52], 5:[self.cell33, self.cell34, self.cell35, self.cell43, self.cell44, self.cell45, self.cell53, self.cell54, self.cell55], 6:[self.cell36, self.cell37, self.cell38, self.cell46, self.cell47, self.cell48, self.cell56, self.cell57, self.cell58], 7:[self.cell60, self.cell61, self.cell62, self.cell70, self.cell71, self.cell72, self.cell80, self.cell81, self.cell82], 8:[self.cell63, self.cell64, self.cell65, self.cell73, self.cell74, self.cell75, self.cell83, self.cell84, self.cell85], 9:[self.cell66, self.cell67, self.cell68, self.cell76, self.cell77, self.cell78, self.cell86, self.cell87, self.cell88]}

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Resolve"))
        self.pushButton_2.setText(_translate("MainWindow", "Load"))
        self.label.setText(_translate("MainWindow", " CONGRATULATIONS !!! "))
        self.pushButton_3.setText(_translate("MainWindow", "Check"))
    
    def resolve(self, result, state):
        state=state
        current_sudoku=np.zeros((9,9))
        current_sudoku[0,0]=int(self.cell00.value())
        current_sudoku[0,1]=int(self.cell01.value())
        current_sudoku[0,2]=int(self.cell02.value())
        current_sudoku[0,3]=int(self.cell03.value())
        current_sudoku[0,4]=int(self.cell04.value())
        current_sudoku[0,5]=int(self.cell05.value())
        current_sudoku[0,6]=int(self.cell06.value())
        current_sudoku[0,7]=int(self.cell07.value())
        current_sudoku[0,8]=int(self.cell08.value())
        current_sudoku[1,0]=int(self.cell10.value())
        current_sudoku[1,1]=int(self.cell11.value())
        current_sudoku[1,2]=int(self.cell12.value())
        current_sudoku[1,3]=int(self.cell13.value())
        current_sudoku[1,4]=int(self.cell14.value())
        current_sudoku[1,5]=int(self.cell15.value())
        current_sudoku[1,6]=int(self.cell16.value())
        current_sudoku[1,7]=int(self.cell17.value())
        current_sudoku[1,8]=int(self.cell18.value())
        current_sudoku[2,0]=int(self.cell20.value())
        current_sudoku[2,1]=int(self.cell21.value())
        current_sudoku[2,2]=int(self.cell22.value())
        current_sudoku[2,3]=int(self.cell23.value())
        current_sudoku[2,4]=int(self.cell24.value())
        current_sudoku[2,5]=int(self.cell25.value())
        current_sudoku[2,6]=int(self.cell26.value())
        current_sudoku[2,7]=int(self.cell27.value())
        current_sudoku[2,8]=int(self.cell28.value())
        current_sudoku[3,0]=int(self.cell30.value())
        current_sudoku[3,1]=int(self.cell31.value())
        current_sudoku[3,2]=int(self.cell32.value())
        current_sudoku[3,3]=int(self.cell33.value())
        current_sudoku[3,4]=int(self.cell34.value())
        current_sudoku[3,5]=int(self.cell35.value())
        current_sudoku[3,6]=int(self.cell36.value())
        current_sudoku[3,7]=int(self.cell37.value())
        current_sudoku[3,8]=int(self.cell38.value())
        current_sudoku[4,0]=int(self.cell40.value())
        current_sudoku[4,1]=int(self.cell41.value())
        current_sudoku[4,2]=int(self.cell42.value())
        current_sudoku[4,3]=int(self.cell43.value())
        current_sudoku[4,4]=int(self.cell44.value())
        current_sudoku[4,5]=int(self.cell45.value())
        current_sudoku[4,6]=int(self.cell46.value())
        current_sudoku[4,7]=int(self.cell47.value())
        current_sudoku[4,8]=int(self.cell48.value())
        current_sudoku[5,0]=int(self.cell50.value())
        current_sudoku[5,1]=int(self.cell51.value())
        current_sudoku[5,2]=int(self.cell52.value())
        current_sudoku[5,3]=int(self.cell53.value())
        current_sudoku[5,4]=int(self.cell54.value())
        current_sudoku[5,5]=int(self.cell55.value())
        current_sudoku[5,6]=int(self.cell56.value())
        current_sudoku[5,7]=int(self.cell57.value())
        current_sudoku[5,8]=int(self.cell58.value())
        current_sudoku[6,0]=int(self.cell60.value())
        current_sudoku[6,1]=int(self.cell61.value())
        current_sudoku[6,2]=int(self.cell62.value())
        current_sudoku[6,3]=int(self.cell63.value())
        current_sudoku[6,4]=int(self.cell64.value())
        current_sudoku[6,5]=int(self.cell65.value())
        current_sudoku[6,6]=int(self.cell66.value())
        current_sudoku[6,7]=int(self.cell67.value())
        current_sudoku[6,8]=int(self.cell68.value())
        current_sudoku[7,0]=int(self.cell70.value())
        current_sudoku[7,1]=int(self.cell71.value())
        current_sudoku[7,2]=int(self.cell72.value())
        current_sudoku[7,3]=int(self.cell73.value())
        current_sudoku[7,4]=int(self.cell74.value())
        current_sudoku[7,5]=int(self.cell75.value())
        current_sudoku[7,6]=int(self.cell76.value())
        current_sudoku[7,7]=int(self.cell77.value())
        current_sudoku[7,8]=int(self.cell78.value())
        current_sudoku[8,0]=int(self.cell80.value())
        current_sudoku[8,1]=int(self.cell81.value())
        current_sudoku[8,2]=int(self.cell82.value())
        current_sudoku[8,3]=int(self.cell83.value())
        current_sudoku[8,4]=int(self.cell84.value())
        current_sudoku[8,5]=int(self.cell85.value())
        current_sudoku[8,6]=int(self.cell86.value())
        current_sudoku[8,7]=int(self.cell87.value())
        current_sudoku[8,8]=int(self.cell88.value())
        sudoku=Sudoku(current_sudoku)
        sudoku.generateCuadrants()
        worker = Worker(sudoku)
        MainWindow.threadpool.start(worker)
        while not state:
            print('el programita esta pensando')
            time.sleep(2)

        if result.astype(int)[0,0]==0:
            self.label.setStyleSheet("background-color: rgba(255,255,255,255);")
            self.label.setText(' This sudoku does not have solution :( ')
            self.label.setStyleSheet('color: rgba(255, 0 , 0, 200)')

        else:
            self.cell00.setProperty('value', int(result[0,0]))
            self.cell01.setProperty('value', int(result[0,1]))
            self.cell02.setProperty('value', int(result[0,2]))
            self.cell03.setProperty('value', int(result[0,3]))
            self.cell04.setProperty('value', int(result[0,4]))
            self.cell05.setProperty('value', int(result[0,5]))
            self.cell06.setProperty('value', int(result[0,6]))
            self.cell07.setProperty('value', int(result[0,7]))
            self.cell08.setProperty('value', int(result[0,8]))
            self.cell10.setProperty('value', int(result[1,0]))
            self.cell11.setProperty('value', int(result[1,1]))
            self.cell12.setProperty('value', int(result[1,2]))
            self.cell13.setProperty('value', int(result[1,3]))
            self.cell14.setProperty('value', int(result[1,4]))
            self.cell15.setProperty('value', int(result[1,5]))
            self.cell16.setProperty('value', int(result[1,6]))
            self.cell17.setProperty('value', int(result[1,7]))
            self.cell18.setProperty('value', int(result[1,8]))
            self.cell20.setProperty('value', int(result[2,0]))
            self.cell21.setProperty('value', int(result[2,1]))
            self.cell22.setProperty('value', int(result[2,2]))
            self.cell23.setProperty('value', int(result[2,3]))
            self.cell24.setProperty('value', int(result[2,4]))
            self.cell25.setProperty('value', int(result[2,5]))
            self.cell26.setProperty('value', int(result[2,6]))
            self.cell27.setProperty('value', int(result[2,7]))
            self.cell28.setProperty('value', int(result[2,8]))
            self.cell30.setProperty('value', int(result[3,0]))
            self.cell31.setProperty('value', int(result[3,1]))
            self.cell32.setProperty('value', int(result[3,2]))
            self.cell33.setProperty('value', int(result[3,3]))
            self.cell34.setProperty('value', int(result[3,4]))
            self.cell35.setProperty('value', int(result[3,5]))
            self.cell36.setProperty('value', int(result[3,6]))
            self.cell37.setProperty('value', int(result[3,7]))
            self.cell38.setProperty('value', int(result[3,8]))
            self.cell40.setProperty('value', int(result[4,0]))
            self.cell41.setProperty('value', int(result[4,1]))
            self.cell42.setProperty('value', int(result[4,2]))
            self.cell43.setProperty('value', int(result[4,3]))
            self.cell44.setProperty('value', int(result[4,4]))
            self.cell45.setProperty('value', int(result[4,5]))
            self.cell46.setProperty('value', int(result[4,6]))
            self.cell47.setProperty('value', int(result[4,7]))
            self.cell48.setProperty('value', int(result[4,8]))
            self.cell50.setProperty('value', int(result[5,0]))
            self.cell51.setProperty('value', int(result[5,1]))
            self.cell52.setProperty('value', int(result[5,2]))
            self.cell53.setProperty('value', int(result[5,3]))
            self.cell54.setProperty('value', int(result[5,4]))
            self.cell55.setProperty('value', int(result[5,5]))
            self.cell56.setProperty('value', int(result[5,6]))
            self.cell57.setProperty('value', int(result[5,7]))
            self.cell58.setProperty('value', int(result[5,8]))
            self.cell60.setProperty('value', int(result[6,0]))
            self.cell61.setProperty('value', int(result[6,1]))
            self.cell62.setProperty('value', int(result[6,2]))
            self.cell63.setProperty('value', int(result[6,3]))
            self.cell64.setProperty('value', int(result[6,4]))
            self.cell65.setProperty('value', int(result[6,5]))
            self.cell66.setProperty('value', int(result[6,6]))
            self.cell67.setProperty('value', int(result[6,7]))
            self.cell68.setProperty('value', int(result[6,8]))
            self.cell70.setProperty('value', int(result[7,0]))
            self.cell71.setProperty('value', int(result[7,1]))
            self.cell72.setProperty('value', int(result[7,2]))
            self.cell73.setProperty('value', int(result[7,3]))
            self.cell74.setProperty('value', int(result[7,4]))
            self.cell75.setProperty('value', int(result[7,5]))
            self.cell76.setProperty('value', int(result[7,6]))
            self.cell77.setProperty('value', int(result[7,7]))
            self.cell78.setProperty('value', int(result[7,8]))
            self.cell80.setProperty('value', int(result[8,0]))
            self.cell81.setProperty('value', int(result[8,1]))
            self.cell82.setProperty('value', int(result[8,2]))
            self.cell83.setProperty('value', int(result[8,3]))
            self.cell84.setProperty('value', int(result[8,4]))
            self.cell85.setProperty('value', int(result[8,5]))
            self.cell86.setProperty('value', int(result[8,6]))
            self.cell87.setProperty('value', int(result[8,7]))
            self.cell88.setProperty('value', int(result[8,8]))

    def compute(self, sudoku):
        sudoku.autoResolve()


    def check(self):
        counter=0
        current_sudoku=np.zeros((9,9))
        current_sudoku[0,0]=int(self.cell00.value())
        current_sudoku[0,1]=int(self.cell01.value())
        current_sudoku[0,2]=int(self.cell02.value())
        current_sudoku[0,3]=int(self.cell03.value())
        current_sudoku[0,4]=int(self.cell04.value())
        current_sudoku[0,5]=int(self.cell05.value())
        current_sudoku[0,6]=int(self.cell06.value())
        current_sudoku[0,7]=int(self.cell07.value())
        current_sudoku[0,8]=int(self.cell08.value())
        current_sudoku[1,0]=int(self.cell10.value())
        current_sudoku[1,1]=int(self.cell11.value())
        current_sudoku[1,2]=int(self.cell12.value())
        current_sudoku[1,3]=int(self.cell13.value())
        current_sudoku[1,4]=int(self.cell14.value())
        current_sudoku[1,5]=int(self.cell15.value())
        current_sudoku[1,6]=int(self.cell16.value())
        current_sudoku[1,7]=int(self.cell17.value())
        current_sudoku[1,8]=int(self.cell18.value())
        current_sudoku[2,0]=int(self.cell20.value())
        current_sudoku[2,1]=int(self.cell21.value())
        current_sudoku[2,2]=int(self.cell22.value())
        current_sudoku[2,3]=int(self.cell23.value())
        current_sudoku[2,4]=int(self.cell24.value())
        current_sudoku[2,5]=int(self.cell25.value())
        current_sudoku[2,6]=int(self.cell26.value())
        current_sudoku[2,7]=int(self.cell27.value())
        current_sudoku[2,8]=int(self.cell28.value())
        current_sudoku[3,0]=int(self.cell30.value())
        current_sudoku[3,1]=int(self.cell31.value())
        current_sudoku[3,2]=int(self.cell32.value())
        current_sudoku[3,3]=int(self.cell33.value())
        current_sudoku[3,4]=int(self.cell34.value())
        current_sudoku[3,5]=int(self.cell35.value())
        current_sudoku[3,6]=int(self.cell36.value())
        current_sudoku[3,7]=int(self.cell37.value())
        current_sudoku[3,8]=int(self.cell38.value())
        current_sudoku[4,0]=int(self.cell40.value())
        current_sudoku[4,1]=int(self.cell41.value())
        current_sudoku[4,2]=int(self.cell42.value())
        current_sudoku[4,3]=int(self.cell43.value())
        current_sudoku[4,4]=int(self.cell44.value())
        current_sudoku[4,5]=int(self.cell45.value())
        current_sudoku[4,6]=int(self.cell46.value())
        current_sudoku[4,7]=int(self.cell47.value())
        current_sudoku[4,8]=int(self.cell48.value())
        current_sudoku[5,0]=int(self.cell50.value())
        current_sudoku[5,1]=int(self.cell51.value())
        current_sudoku[5,2]=int(self.cell52.value())
        current_sudoku[5,3]=int(self.cell53.value())
        current_sudoku[5,4]=int(self.cell54.value())
        current_sudoku[5,5]=int(self.cell55.value())
        current_sudoku[5,6]=int(self.cell56.value())
        current_sudoku[5,7]=int(self.cell57.value())
        current_sudoku[5,8]=int(self.cell58.value())
        current_sudoku[6,0]=int(self.cell60.value())
        current_sudoku[6,1]=int(self.cell61.value())
        current_sudoku[6,2]=int(self.cell62.value())
        current_sudoku[6,3]=int(self.cell63.value())
        current_sudoku[6,4]=int(self.cell64.value())
        current_sudoku[6,5]=int(self.cell65.value())
        current_sudoku[6,6]=int(self.cell66.value())
        current_sudoku[6,7]=int(self.cell67.value())
        current_sudoku[6,8]=int(self.cell68.value())
        current_sudoku[7,0]=int(self.cell70.value())
        current_sudoku[7,1]=int(self.cell71.value())
        current_sudoku[7,2]=int(self.cell72.value())
        current_sudoku[7,3]=int(self.cell73.value())
        current_sudoku[7,4]=int(self.cell74.value())
        current_sudoku[7,5]=int(self.cell75.value())
        current_sudoku[7,6]=int(self.cell76.value())
        current_sudoku[7,7]=int(self.cell77.value())
        current_sudoku[7,8]=int(self.cell78.value())
        current_sudoku[8,0]=int(self.cell80.value())
        current_sudoku[8,1]=int(self.cell81.value())
        current_sudoku[8,2]=int(self.cell82.value())
        current_sudoku[8,3]=int(self.cell83.value())
        current_sudoku[8,4]=int(self.cell84.value())
        current_sudoku[8,5]=int(self.cell85.value())
        current_sudoku[8,6]=int(self.cell86.value())
        current_sudoku[8,7]=int(self.cell87.value())
        current_sudoku[8,8]=int(self.cell88.value())
        sudoku=Sudoku(current_sudoku)
        sudoku.generateCuadrants()
        for row in range(0,9):
            for col in range(0,9):
                if ((not sudoku.checkRow(row, col)) or (not sudoku.checkRowCompleted(row))):
                    counter+=1
                    for cell in self.row_dict[row]:
                        cell.setStyleSheet("background-color: rgba(255,0,0,150);")
                    QtTest.QTest.qWait(1500)
                    for cell in self.row_dict[row]:
                        cell.setStyleSheet("background-color: rgba(255,255,255,0);")
                    break

        for col in range(0,9):
            for row in range(0,9):
                if ((not sudoku.checkColumn(row, col)) or (not sudoku.checkColumnCompleted(col))):
                    counter+=1
                    for cell in self.col_dict[col]:
                        cell.setStyleSheet("background-color: rgba(255,0,0,150);")
                    QtTest.QTest.qWait(1500)
                    for cell in self.col_dict[col]:                
                        cell.setStyleSheet("background-color: rgba(255,255,255,0);")
                    break                  
        for row in range(0,9):
            for col in range(0,9):
                if ((not sudoku.checkCuadrant(sudoku.getCuadrant(row,col),row, col)) or (not sudoku.checkCuadrantCompleted(sudoku.getCuadrant(row,col)))):
                    counter+=1
                    for cell in self.cuadrant_dict[3*int(row/3)+int(col/3)+1]:
                        cell.setStyleSheet("background-color: rgba(255,0,0,150);")
                    QtTest.QTest.qWait(1500)
                    for cell in self.cuadrant_dict[3*int(row/3)+int(col/3)+1]:
                        cell.setStyleSheet("background-color: rgba(255,255,255,0);")
                    break                  
        if counter==0:
            self.label.setStyleSheet("background-color: rgba(255,255,255,0);")
            self.label.setStyleSheet('color: rgba(0, 255 , 0, 200)')
            QtTest.QTest.qWait(1500)
            self.label.setStyleSheet('color: rgba(0,255,255,0)')

            

    def load(self):
        
        options = QtWidgets.QFileDialog.Options()
        options |= QtWidgets.QFileDialog.DontUseNativeDialog
        filename, _ = QtWidgets.QFileDialog.getOpenFileName(None,"QFileDialog.getOpenFileName()","","All Files (*);;Python Files (*.py)",options=options)
        if filename:
            print(filename)
            #path=os.path.dirname(os.path.abspath(__file__))
            #fname='misudoku.pkl'
            #f=os.path.join(path, filename)
            sudoku=joblib.load(filename)
            self.cell00.setProperty('value', int(sudoku[0,0]))
            self.cell01.setProperty('value', int(sudoku[0,1]))
            self.cell02.setProperty('value', int(sudoku[0,2]))
            self.cell03.setProperty('value', int(sudoku[0,3]))
            self.cell04.setProperty('value', int(sudoku[0,4]))
            self.cell05.setProperty('value', int(sudoku[0,5]))
            self.cell06.setProperty('value', int(sudoku[0,6]))
            self.cell07.setProperty('value', int(sudoku[0,7]))
            self.cell08.setProperty('value', int(sudoku[0,8]))
            self.cell10.setProperty('value', int(sudoku[1,0]))
            self.cell11.setProperty('value', int(sudoku[1,1]))
            self.cell12.setProperty('value', int(sudoku[1,2]))
            self.cell13.setProperty('value', int(sudoku[1,3]))
            self.cell14.setProperty('value', int(sudoku[1,4]))
            self.cell15.setProperty('value', int(sudoku[1,5]))
            self.cell16.setProperty('value', int(sudoku[1,6]))
            self.cell17.setProperty('value', int(sudoku[1,7]))
            self.cell18.setProperty('value', int(sudoku[1,8]))
            self.cell20.setProperty('value', int(sudoku[2,0]))
            self.cell21.setProperty('value', int(sudoku[2,1]))
            self.cell22.setProperty('value', int(sudoku[2,2]))
            self.cell23.setProperty('value', int(sudoku[2,3]))
            self.cell24.setProperty('value', int(sudoku[2,4]))
            self.cell25.setProperty('value', int(sudoku[2,5]))
            self.cell26.setProperty('value', int(sudoku[2,6]))
            self.cell27.setProperty('value', int(sudoku[2,7]))
            self.cell28.setProperty('value', int(sudoku[2,8]))
            self.cell30.setProperty('value', int(sudoku[3,0]))
            self.cell31.setProperty('value', int(sudoku[3,1]))
            self.cell32.setProperty('value', int(sudoku[3,2]))
            self.cell33.setProperty('value', int(sudoku[3,3]))
            self.cell34.setProperty('value', int(sudoku[3,4]))
            self.cell35.setProperty('value', int(sudoku[3,5]))
            self.cell36.setProperty('value', int(sudoku[3,6]))
            self.cell37.setProperty('value', int(sudoku[3,7]))
            self.cell38.setProperty('value', int(sudoku[3,8]))
            self.cell40.setProperty('value', int(sudoku[4,0]))
            self.cell41.setProperty('value', int(sudoku[4,1]))
            self.cell42.setProperty('value', int(sudoku[4,2]))
            self.cell43.setProperty('value', int(sudoku[4,3]))
            self.cell44.setProperty('value', int(sudoku[4,4]))
            self.cell45.setProperty('value', int(sudoku[4,5]))
            self.cell46.setProperty('value', int(sudoku[4,6]))
            self.cell47.setProperty('value', int(sudoku[4,7]))
            self.cell48.setProperty('value', int(sudoku[4,8]))
            self.cell50.setProperty('value', int(sudoku[5,0]))
            self.cell51.setProperty('value', int(sudoku[5,1]))
            self.cell52.setProperty('value', int(sudoku[5,2]))
            self.cell53.setProperty('value', int(sudoku[5,3]))
            self.cell54.setProperty('value', int(sudoku[5,4]))
            self.cell55.setProperty('value', int(sudoku[5,5]))
            self.cell56.setProperty('value', int(sudoku[5,6]))
            self.cell57.setProperty('value', int(sudoku[5,7]))
            self.cell58.setProperty('value', int(sudoku[5,8]))
            self.cell60.setProperty('value', int(sudoku[6,0]))
            self.cell61.setProperty('value', int(sudoku[6,1]))
            self.cell62.setProperty('value', int(sudoku[6,2]))
            self.cell63.setProperty('value', int(sudoku[6,3]))
            self.cell64.setProperty('value', int(sudoku[6,4]))
            self.cell65.setProperty('value', int(sudoku[6,5]))
            self.cell66.setProperty('value', int(sudoku[6,6]))
            self.cell67.setProperty('value', int(sudoku[6,7]))
            self.cell68.setProperty('value', int(sudoku[6,8]))
            self.cell70.setProperty('value', int(sudoku[7,0]))
            self.cell71.setProperty('value', int(sudoku[7,1]))
            self.cell72.setProperty('value', int(sudoku[7,2]))
            self.cell73.setProperty('value', int(sudoku[7,3]))
            self.cell74.setProperty('value', int(sudoku[7,4]))
            self.cell75.setProperty('value', int(sudoku[7,5]))
            self.cell76.setProperty('value', int(sudoku[7,6]))
            self.cell77.setProperty('value', int(sudoku[7,7]))
            self.cell78.setProperty('value', int(sudoku[7,8]))
            self.cell80.setProperty('value', int(sudoku[8,0]))
            self.cell81.setProperty('value', int(sudoku[8,1]))
            self.cell82.setProperty('value', int(sudoku[8,2]))
            self.cell83.setProperty('value', int(sudoku[8,3]))
            self.cell84.setProperty('value', int(sudoku[8,4]))
            self.cell85.setProperty('value', int(sudoku[8,5]))
            self.cell86.setProperty('value', int(sudoku[8,6]))
            self.cell87.setProperty('value', int(sudoku[8,7]))
            self.cell88.setProperty('value', int(sudoku[8,8]))

class WorkerSignals(QtCore.QObject):

    state = QtCore.pyqtSignal(bool)
    result = QtCore.pyqtSignal(Sudoku)

class Worker(QtCore.QRunnable):

    signal_sudoku=QtCore.pyqtSignal(Sudoku)
    signal_state=QtCore.pyqtSignal(bool)

    def __init__(self, sudoku):
        super(Worker, self).__init__()
        self.sudoku=sudoku
        self.signal_sudoku.connect(Ui_MainWindow.resolve)
        self.signal_state.connect(Ui_MainWindow.resolve)
        self.signals=WorkerSignals()
        
    @QtCore.pyqtSlot()
    def run(self):
        result=self.sudoku.autoResolve()
        self.signal_sudoku.emit(result)
        state=True
        self.signal_state.emit(state)

class MainWindow(QtWidgets.QMainWindow):
    def __init__(self, *args, **kwargs):
        super(MainWindow, self).__init__(*args, **kwargs)
        self.threadpool = QtCore.QThreadPool()

   
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = MainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

